### ISSUE TITLE
Can't make it process videoes or images.

### ISSUE THREAD

**Issue by AIMads** [MPForte/SGNify#1]
Hey great work!

I can't get it to run on any videoes, get the following error log:

Segmenting signs...
/home/mil/anaconda3/envs/sgnify/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/mil/anaconda3/envs/sgnify/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/home/mil/Desktop/SGNify/sgnify.py", line 482, in <module>
    main(args)
  File "/home/mil/Desktop/SGNify/sgnify.py", line 369, in main
    segment_signs(openpose_folder=openpose_folder, output_path=segment_path)
  File "/home/mil/Desktop/SGNify/utils/segment_signs.py", line 19, in segment_signs
    y_elb = np.max(y[[3, 6]][:, ~np.any(c[[3, 6]], axis=0)])
  File "/home/mil/anaconda3/envs/sgnify/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 2810, in max
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/home/mil/anaconda3/envs/sgnify/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by AIMads** [comment]
Fixed happens if you use image_path instead of video path, silly mistake by me
