### ISSUE TITLE
Still issues with interpolate.py

### ISSUE THREAD

**Issue by AIMads** [MPForte/SGNify#11]
Tried @athena913 fix to the interpolate.py issue, but still experience problems as im now able to call the function, error log:

Interpolating right hand...
Traceback (most recent call last):
  File "/home/humaid/Desktop/SGNify/sgnify.py", line 482, in <module>
    required=False,
  File "/home/humaid/Desktop/SGNify/sgnify.py", line 414, in main
    print(args.sign_class)
  File "/home/humaid/Desktop/SGNify/utils/rps.py", line 178, in compute_rps
    interpolate(
  File "/home/humaid/Desktop/SGNify/utils/rps.py", line 200, in interpolate
    return run([ "python", "utils/interpolate.py", "--pkl", pkl_1, pkl_2, "--save_folder", save_folder, "--config", "cfg_files/fit_smplifyx_ref_sv.yaml", "--reference_start", str(reference_start), "--reference_end", str(reference_end), "--end_frame", str(end_frame), ], check=True, )
  File "/home/humaid/mambaforge/envs/sgnify/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'utils/interpolate.py', '--pkl', PosixPath('/home/humaid/Desktop/SGNify/output/s_5440/.tmp/rps/ref_right_1.pkl'), PosixPath('/home/humaid/Desktop/SGNify/output/s_5440/.tmp/rps/ref_right_2.pkl'), '--save_folder', PosixPath('/home/humaid/Desktop/SGNify/output/s_5440/.tmp/rps/interp_right'), '--config', 'cfg_files/fit_smplifyx_ref_sv.yaml', '--reference_start', '20', '--reference_end', '275', '--end_frame', '312']' returned non-zero exit status 1.

**Comment by AIMads** [comment]
This was the CMD_PARSER issue
