### ISSUE TITLE
sgnify main function is unstable and crashes at random it seems like, something is fragile. 

### ISSUE THREAD

**Issue by AIMads** [MPForte/SGNify#12]
The system breaks randomly, it is able to handle some iterations but will at some point break.

Error log:

 26%|██▌       | 7/27 [09:55<27:19, 81.97s/it]Traceback (most recent call last):
  File "/home/humaid/Desktop/SGNify/smplifyx/main.py", line 261, in <module>
    main(**args)
  File "/home/humaid/Desktop/SGNify/smplifyx/main.py", line 232, in main
    fit_single_frame(img, keypoints[[0]],
  File "/home/humaid/Desktop/SGNify/smplifyx/fit_single_frame.py", line 650, in fit_single_frame
    final_loss_val = monitor.run_fitting(
  File "/home/humaid/Desktop/SGNify/smplifyx/fitting.py", line 176, in run_fitting
    loss = optimizer.step(closure)
  File "/home/humaid/mambaforge/envs/sgnify/lib/python3.10/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "/home/humaid/Desktop/SGNify/smplifyx/optimizers/trust_region_newton_cg.py", line 301, in step
    param_step, hit_boundary = self._solve_trust_reg_subproblem(
  File "/home/humaid/mambaforge/envs/sgnify/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/humaid/Desktop/SGNify/smplifyx/optimizers/trust_region_newton_cg.py", line 277, in _solve_trust_reg_subproblem
    raise RuntimeError
RuntimeError
 26%|██▌       | 7/27 [10:26<29:50, 89.53s/it]
Traceback (most recent call last):
  File "/home/humaid/Desktop/SGNify/sgnify.py", line 492, in <module>
    main(args)
  File "/home/humaid/Desktop/SGNify/sgnify.py", line 452, in main
    run_sgnify(
  File "/home/humaid/Desktop/SGNify/sgnify.py", line 251, in run_sgnify
    call_sgnify(
  File "/home/humaid/Desktop/SGNify/sgnify.py", line 138, in call_sgnify
    return run(
  File "/home/humaid/mambaforge/envs/sgnify/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'smplifyx/main.py', '--config', 'cfg_files/fit_sgnifyx_sv.yaml', '--output_folder', PosixPath('/home/humaid/Desktop/SGNify/output/A-KASSE'), '--data_folder', PosixPath('/home/humaid/Desktop/SGNify/output/A-KASSE/.tmp/tmp/data'), '--prev_res_path', PosixPath('/home/humaid/Desktop/SGNify/output/A-KASSE/results/007.pkl'), '--expression_precomputed', 'True', '--expression_path', PosixPath('/home/humaid/Desktop/SGNify/output/A-KASSE/.tmp/spectre/spectre_8.pkl'), '--use_symmetry', 'True', '--symmetry_weight', '90', '--left_handpose_path', PosixPath('/home/humaid/Desktop/SGNify/output/A-KASSE/.tmp/rps/ref_left.pkl'), '--left_reference_weight', '90', '--right_handpose_path', PosixPath('/home/humaid/Desktop/SGNify/output/A-KASSE/.tmp/rps/ref_right.pkl'), '--right_reference_weight', '90', '--beta_precomputed', 'True']' returned non-zero exit status 1.

**Comment by mhannani** [comment]
@AIMads Did you manage to fix that issue you were facing?

**Comment by MPForte** [comment]
Please refer to this:
https://github.com/MPForte/SGNify/issues/9
