### ISSUE TITLE
Running spectre results in issue with Resnet50_final

### ISSUE THREAD

**Issue by AIMads** [MPForte/SGNify#3]
Hey

I get the following error message, when running the spectre part of the code, it seems like the model is corrupted or something bad happens when downloaded:

Error log:

/home/mil/anaconda3/envs/sgnify/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/mil/anaconda3/envs/sgnify/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to /home/mil/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth
100%|████████████████████████████████████████████████████████████████████████████| 97.8M/97.8M [00:08<00:00, 11.7MB/s]
Downloading: "https://github.com/pytorch/vision/zipball/v0.8.1" to /home/mil/.cache/torch/hub/v0.8.1.zip
/home/mil/anaconda3/envs/sgnify/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=MobileNet_V2_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V2_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/mobilenet_v2-b0353104.pth" to /home/mil/.cache/torch/hub/checkpoints/mobilenet_v2-b0353104.pth
100%|████████████████████████████████████████████████████████████████████████████| 13.6M/13.6M [00:01<00:00, 11.5MB/s]
An exception occurred in telemetry logging.Disabling telemetry to prevent further exceptions.
Traceback (most recent call last):
  File "/home/mil/anaconda3/envs/sgnify/lib/python3.10/site-packages/iopath/common/file_io.py", line 946, in __log_tmetry_keys
    handler.log_event()
  File "/home/mil/anaconda3/envs/sgnify/lib/python3.10/site-packages/iopath/common/event_logger.py", line 97, in log_event
    del self._evt
AttributeError: _evt
/home/mil/anaconda3/envs/sgnify/lib/python3.10/site-packages/pytorch3d/io/obj_io.py:548: UserWarning: Mtl file does not exist: /home/mil/Desktop/SGNify/spectre/data/template.mtl
  warnings.warn(f"Mtl file does not exist: {f}")
/home/mil/anaconda3/envs/sgnify/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/mil/Desktop/SGNify/utils/spectre_demo.py", line 228, in <module>
    main(parser.parse_args())
  File "/home/mil/Desktop/SGNify/utils/spectre_demo.py", line 84, in main
    landmarks = extract_frames(image_paths)
  File "/home/mil/Desktop/SGNify/utils/spectre_demo.py", line 31, in extract_frames
    face_tracker = FaceTracker()
  File "/home/mil/Desktop/SGNify/spectre/external/Visual_Speech_Recognition_for_Multiple_Languages/tracker/face_tracker.py", line 23, in __init__
    self.face_detector = RetinaFacePredictor(
  File "/home/mil/Desktop/SGNify/spectre/external/face_detection/ibug/face_detection/retina_face/retina_face_predictor.py", line 28, in __init__
    pretrained_dict = torch.load(model.weights, map_location=self.device)
  File "/home/mil/anaconda3/envs/sgnify/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/mil/anaconda3/envs/sgnify/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by AIMads** [comment]
Can be fixed by downloading the model through http and then copying it over
